### ISSUE TITLE
Better use of the display

### ISSUE THREAD

**Issue by adriaaah** [adriaaah/monit-dashboard#10]
Since #9 (thank you, @saravanan30erd )a dashboard is being displayed.
However the server list remains on top and most of the area is being used by the dashboard.
Since most of displays are horizontal we could do a better use of the whole area by splitting the screen vertically instead of horizontally (e.g. server list on a left pane and the dashboard on the right).

**Comment by saravanan30erd** [comment]
@adriaaah I will work on this weekend.
