### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by jonhattan** [adriaaah/monit-dashboard#20]
Hi there,

great dashboard!

Docker build instructions in README are wrong. I managed to bring it up with:

```
docker build -t monit-dashboard .
docker run -v $(pwd)/conf:/app/conf -p 8080:8080 monit-dashboard
```

---

What about publishing an image to the Docker hub?

**Comment by adriaaah** [comment]
Answering your question about publishing an image on Docker Hub, honestly I'd consider that once/if the app works with Python 3.

Thanks for your feedback.
I'm closing the issue as I understand it's related to `Dockerfile` but feel free to raise another one to discuss it.
